title: What to Eat
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of recipe.
baseurl: "/what-to-eat" # the subpath of your site, e.g. /blog
url: "https://hmenorjr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hmenorjr
github_username:  hmenorjr
linkedin_username: hmenorjr

# Build settings
theme: minima
plugins:
  - jekyll-feed